on:
    pull_request:
        types: [opened, edited, reopened]

jobs:
    autoclose:
        runs-on: ubuntu-latest
        steps:
            - name: Close Pull Request
              uses: peter-evans/close-pull@v2
              with:
                  comment: |
                      Thanks for your pull request! We love contributions.

                      However, this repository is a read-only export of one boilerplate of its main repository.

                      If you want to report or contribute, you should instead open your issue on the main repository:

                      https://github.com/CrystallizeAPI/superfast-boilerplates

                      PS: if you haven't already, please add tests.
